name: Linux
run-name: KomaruGram for Linux — ${{ github.ref_name }}

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tagname:
        description: 'tagname'
        type: string
        required: true
      pkgrel:
        description: pkgrel
        type: number
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tagname: ${{ steps.tagname.outputs.tagname }}
    env:
      IMAGE_TAG: komarugram:build

    steps:
      - name: Set TAGNAME
        id: tagname
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAGNAME="${{ github.event.inputs.tagname }}"
          else
            TAGNAME="${GITHUB_REF#refs/tags/}"
          fi
          echo "TAGNAME=$TAGNAME" >> $GITHUB_ENV
          echo "tagname=$TAGNAME" >> $GITHUB_OUTPUT

      - name: Free up some disk space.
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          tool-cache: true

      - name: Clone.
        uses: actions/checkout@v7
        with:
          submodules: recursive
          ref: ${{ env.TAGNAME }}

      - name: Pull Docker
        run: |
          docker pull ghcr.io/telegramdesktop/tdesktop/centos_env
          docker tag ghcr.io/telegramdesktop/tdesktop/centos_env $IMAGE_TAG

      - name: KomaruGram build
        run: |
          docker run --rm \
          -u $(id -u) \
          -v $PWD:/usr/src/tdesktop \
          $IMAGE_TAG \
          /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
          -D CMAKE_CONFIGURATION_TYPES=Release \
          -D CMAKE_INSTALL_PREFIX="/usr" \
          -D TDESKTOP_API_ID=${{ secrets.TDESKTOP_API_ID }} \
          -D TDESKTOP_API_HASH=${{ secrets.TDESKTOP_API_HASH }} \
          -D DESKTOP_APP_DISABLE_AUTOUPDATE=ON

      - name: Create Tar
        run: |
          cd out/install
          tar -I 'zstd -T0 --ultra -22' -cvf KomaruGram-${{ env.TAGNAME }}.tar.zst usr

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: KomaruGram-${{ env.TAGNAME }}
          path: out/install/KomaruGram-${{ env.TAGNAME }}.tar.zst

      - name: Upload artifact to Release
        uses: softprops/action-gh-release@v3
        with:
          name: KomaruGram ${{ env.TAGNAME }}
          tag_name: ${{ env.TAGNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: out/install/KomaruGram-${{ env.TAGNAME }}.tar.zst
